// Generated by CoffeeScript 1.8.0
(function() {
  var Schema, TestModel, TestSchema, mocha, mongoose, should, timestamp;

  mocha = require("mocha");

  should = require("should");

  mongoose = require("mongoose");

  Schema = mongoose.Schema;

  timestamp = require("../../plugins/timestamp");

  TestSchema = new Schema({});

  TestSchema.plugin(timestamp);

  TestModel = mongoose.model("Test", TestSchema);

  module.exports = TestModel;

}).call(this);
