// Generated by CoffeeScript 1.8.0
(function() {
  var Schema, TestCustomModel, TestCustomSchema, mocha, mongoose, should, timestamp;

  mocha = require("mocha");

  should = require("should");

  mongoose = require("mongoose");

  Schema = mongoose.Schema;

  timestamp = require("../../plugins/timestamp");

  TestCustomSchema = new Schema({});

  TestCustomSchema.plugin(timestamp, {
    createdAt: "posted",
    updatedAt: "updated"
  });

  TestCustomModel = mongoose.model("TestCustom", TestCustomSchema);

  module.exports = module.exports = TestCustomModel;

}).call(this);
