// Generated by CoffeeScript 1.8.0
(function() {
  var dateJSON, defaults;

  defaults = {
    createdAt: "createdAt",
    updatedAt: "updatedAt"
  };

  dateJSON = function(key) {
    var json;
    json = {};
    json[key] = Date;
    return json;
  };

  module.exports = exports.timestamp = function(schema, options) {
    var createdAt, updatedAt;
    createdAt = options && options.createdAt ? options.createdAt : defaults.createdAt;
    updatedAt = options && options.updatedAt ? options.updatedAt : defaults.updatedAt;
    schema.add(dateJSON(createdAt));
    schema.add(dateJSON(updatedAt));
    return schema.pre("save", function(next) {
      var timestamp;
      timestamp = Date.now();
      if (this[createdAt] == null) {
        this[createdAt] = timestamp;
      }
      this[updatedAt] = timestamp;
      return next();
    });
  };

}).call(this);
